CREATE USER app_ia WITH PASSWORD 'app123';

GRANT CONNECT ON DATABASE iadb TO app_ia;

\connect iadb

GRANT USAGE ON SCHEMA public TO app_ia;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_ia;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_ia;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_ia;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO app_ia;
